// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bercario.Models;

#nullable disable

namespace bercario.Migrations
{
    [DbContext(typeof(BercarioContexto))]
    partial class BercarioContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaeParto", b =>
                {
                    b.Property<int>("MaesId")
                        .HasColumnType("int");

                    b.Property<int>("PartosId")
                        .HasColumnType("int");

                    b.HasKey("MaesId", "PartosId");

                    b.HasIndex("PartosId");

                    b.ToTable("MaeParto");
                });

            modelBuilder.Entity("MedicoParto", b =>
                {
                    b.Property<int>("MedicosId")
                        .HasColumnType("int");

                    b.Property<int>("PartosId")
                        .HasColumnType("int");

                    b.HasKey("MedicosId", "PartosId");

                    b.HasIndex("PartosId");

                    b.ToTable("MedicoParto");
                });

            modelBuilder.Entity("bercario.Models.Bebe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_Nascimento");

                    b.Property<int>("MaeId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Mae");

                    b.Property<int>("PartoId")
                        .HasColumnType("int")
                        .HasColumnName("Id_Parto");

                    b.Property<decimal>("PesoNascimento")
                        .HasColumnType("decimal(4,3)")
                        .HasColumnName("Peso_Nascimento");

                    b.HasKey("Id");

                    b.HasIndex("MaeId");

                    b.HasIndex("PartoId");

                    b.ToTable("Bebe", (string)null);
                });

            modelBuilder.Entity("bercario.Models.Mae", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mae", (string)null);
                });

            modelBuilder.Entity("bercario.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Celular")
                        .HasColumnType("int");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Medico", (string)null);
                });

            modelBuilder.Entity("bercario.Models.Parto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataParto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HorarioParto")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int")
                        .HasColumnName("Id_medico");

                    b.HasKey("Id");

                    b.ToTable("Parto", (string)null);
                });

            modelBuilder.Entity("MaeParto", b =>
                {
                    b.HasOne("bercario.Models.Mae", null)
                        .WithMany()
                        .HasForeignKey("MaesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bercario.Models.Parto", null)
                        .WithMany()
                        .HasForeignKey("PartosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicoParto", b =>
                {
                    b.HasOne("bercario.Models.Medico", null)
                        .WithMany()
                        .HasForeignKey("MedicosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bercario.Models.Parto", null)
                        .WithMany()
                        .HasForeignKey("PartosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bercario.Models.Bebe", b =>
                {
                    b.HasOne("bercario.Models.Mae", "Mae")
                        .WithMany()
                        .HasForeignKey("MaeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bercario.Models.Parto", "Parto")
                        .WithMany()
                        .HasForeignKey("PartoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mae");

                    b.Navigation("Parto");
                });
#pragma warning restore 612, 618
        }
    }
}
